Add i18n support using java property files
bisq-network/bisq-mobile pull request #134
Opened 2024-12-20 11:15 UTC by HenrikJannsen

Add i18n support using java property files.
Not working yet on ios.
Processing of the file content need more work (manual linebreaks not detected yet) and testing.

2024-12-23 06:12 UTC, rodvar requested changes
<img width="409" alt="Screenshot 2024-12-23 at 11 50 14" src="https://github.com/user-attachments/assets/d6fc0857-1975-4a30-aa19-4957c346e07c" />

for russian chars are not displated properly, probably our current font doesn't support cyrilic ?

I fixed a crash when switching languages, and also detected device language.

I've spent almost 3 hours trying it to get the resources in iOS and couldn't make it (tried from xcode as well). 

I think let's parked this one for now and come back to it later down. the road when we are at the polishing stage for MVP?

2024-12-23 06:12 UTC, rodvar commented on shared/domain/src/commonMain/kotlin/network/bisq/mobile/i18n/I18nSupport.kt
> +fun String.i18n(vararg arguments: Any): String {
great kotlin usage for this particular use case

2024-12-23 08:44 UTC, HenrikJannsen commented
> for russian chars are not displated properly, probably our current font doesn't support cyrilic ? 

Yes, looks like a font issue. We need to have the files in UTF8 encoding then all languages should work.
We have to test the IBMPlexSans if it works well with all languages. I hope so, but in Bisq2 we don't have the more challenging languages like Chinese, Japanese, Vietnamese, Thai,... yet.

> I've spent almost 3 hours trying it to get the resources in iOS and couldn't make it (tried from xcode as well).

Oh, seems to be not that easy. ChatGPT told me its doable and suggested various things but non worked out. 
Yes, lets park it then... I am just a bit concerned that with getting the current use cases (incl. create/take offer) more polished that we need to handle quite a lot of strings and often with parameters, so some work need to be invested which might get later be re-done.

2024-12-25 23:46 UTC, rodvar commented
probably good to give priority to this one https://github.com/bisq-network/bisq-mobile/pull/140 when we re-engage with this task

2025-01-07 07:26 UTC, closed without merging