Add domain for user profile
bisq-network/bisq-mobile pull request #62
Opened 2024-11-17 17:01 UTC by HenrikJannsen

2024-11-19 00:05 UTC, rodvar requested changes
great work @HenrikJannsen 

## Runtime

 - I've tested in android pixel 6 (crashes, but expected from your comments) and in emulator. I'll test in all 3 apps on once this first pass of review gets done
 - can get the emulator to run and communicate with running local bisq2-rest-api
 - can see the profile creation working in the logs and the screen 
 - however, I can't go past the screen when clicking next nothing happens and no error is logged
  - some other errors seen:
  ```
  kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'error' at path: $`
                                                                                                     Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
                                                                                                     JSON input: {"error":"Could not find a selected user identity"}
```

## Code

I don't wanna be too verbose here, I think when you read my individual comments you'll find the resolution to our discussions.  Please reach out if something is not clear.

Regarding the Ktor addition. I was working on this as well but in a separate new `networking` module in an effort to avoid making the androidModule grasp those dependencies when its not gonna be used. 

I think I'll drop that for now until we get this one to be merged and then work on that refactor later on.

I contribute with you by finishing the lifecycle setup so you can reuse in your PR as well, might also include the solution for the Dispatchers.IO for you
cheers!

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidClient/build.gradle.kts
> +    implementation("io.ktor:ktor-client-cio:3.0.1")
please use toml syntax

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidClient/src/androidMain/kotlin/network/bisq/mobile/client/MainApplication.kt
> +            modules(listOf(domainModule, presentationModule, androidClientModule))
good name change

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidClient/src/androidMain/kotlin/network/bisq/mobile/client/di/AndroidClientModule.kt
> +    single<UserProfileModel> { ClientUserProfileModel() }
Having a singleton domain model is discouraged. Better to have a singleton repository that holds the domain model obj whichever that is.

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidClient/src/androidMain/kotlin/network/bisq/mobile/client/di/AndroidClientModule.kt
> +    single { ApiRequestService("10.0.2.2") }
we can eventually have an EnvironmentProvider or similar that returns the right host details

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/AndroidApplicationService.kt
> +    init {
this static initialization code has been moved to androidNode MainApplication#setupBisqCoreStatics() - please consider moving updates to this code if any there or removing it from MainApplication if that's not possible anymore

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/di/AndroidNodeModule.kt
> +    single { AndroidApplicationService.Supplier() }
nice hack. Shouldn't then the AndroidApplicationService instance be configured here, and the supplier inyected into that service to provide for all the rest of the instances?

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/domain/user_profile/NodeUserProfileServiceFacade.kt
> +    override val model: UserProfileModel,
service should receive the corresponding user service repository instead of the domain model

2024-11-19 00:05 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/domain/user_profile/NodeUserProfileServiceFacade.kt
> +    override suspend fun generateKeyPair() {
your approach is great, the only difference to comply with the bisq-mobile architecture is that here the model should be fetched from the repository (if existent, otherwise created()) , then modified as it is right now, and finally call repository.update(model) to impact the changes. In that way any view registered to observe the reposiutory model can update itself if needs to with the updated model :)

same applies for the rest of this service methods

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/build.gradle.kts
> +    kotlin("plugin.serialization") version "2.0.21"
please use toml syntax, see other plugins for examples

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/build.gradle.kts
> +            implementation("io.ktor:ktor-client-core:3.0.1") {
plase use toml syntax (libs.kotlinx...)

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/service/ApiRequestService.kt
> +class ApiRequestService(host: String) {
please define and configure the Ktor HttpClient in a new networkingModule in the di subfolder of this module.

then inject it to this class instance in its di module. This also avoids duplicated code found in this class methods

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/ClientUserProfileServiceFacade.kt
> +    // TODO Dispatchers.IO is not supported on iOS. Either customize or find whats on iOS appropriate.
we need to have a expect/actual coroutine dispatcher in the shared/domain and use it for every IO call to solve this issue.

something like this

```
// commonMain

import kotlinx.coroutines.CoroutineDispatcher

expect val BackgroundDispatcher: CoroutineDispatcher


// androidMain
actual val BackgroundDispatcher: CoroutineDispatcher = Dispatchers.IO

// iosMain
actual val BackgroundDispatcher: CoroutineDispatcher = Dispatchers.Default

// example usage
private val coroutineScope = CoroutineScope(BackgroundDispatcher)
```

Dispatchers.Main can still be used without needing any extra platform-based setup.

You can do this now or we can refactor after we merge this one, up to you.

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/ClientUserProfileServiceFacade.kt
> +class ClientUserProfileServiceFacade(
I have several questions on this one.

 1) why do we need this? for the `xClients` , shouldn't the profile management be delegated to the trusted node? so I would expect to have some ktor call here to an api that returns my profile
  2) if we need this, can't we avoid all the code duplication found here compared to the UserProfileServiceFacade for the node?  why are both definitions necessary?

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/CreateUserIdentityRequest.kt
> +package network.bisq.mobile.domain.client.main.user_profile
should we use `dto` subpackage here?

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/domain/data/repository/Repositories.kt
> +class UserProfileRepository(val model: UserProfileModel, val service: UserProfileServiceFacade)
please do not inject domain models directly, use repositories instead

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/domain/user/profile/UserProfile.kt
> +data class UserProfile(
please extend BaseModel class for domain models and use package domain/model (you can create subpackages there as you please)

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/domain/user_profile/UserProfileServiceFacade.kt
> +interface UserProfileServiceFacade {
key interface well documented - excellent work

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/domain/user_profile/UserProfileServiceFacade.kt
> +    val model: UserProfileModel
please make the service depend on the corresponding repository instead of the model directly - see [dependency graph here for more details](https://github.com/bisq-network/bisq-mobile/blob/main/bisqapps/README.md#app-architecture-design-choice)

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/uicases/startup/CreateProfilePresenter.kt
> +) : BasePresenter(mainPresenter) {
not opposed on removing the interface for this particular case

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/uicases/startup/CreateProfilePresenter.kt
> +    private val userProfileModel = userProfileRepository.model
please do not depend on domain model directly, use the corresponding repository instead.

There is a handy BasePresenter protected helper method to connect the view straight to the repository model field that is needed.

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/uicases/startup/CreateProfilePresenter.kt
> +    // Called from the screen atm, until the BasePresenter methods work
this refers to the specific view presenter not being called the moment its view gets rendered I guess - is that correct?

We basically need to tell the presenter when the view is rendering I have that on another branch but haven't pushed it yet, probably finish it today and let you know so you can rebase and apply :)

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/uicases/startup/CreateProfileScreen.kt
> +        presenter.onLaunched()
oh you've linked it here, this works. Maybe use the onViewAttached instead of onLaunched?
I'll let you know when I add it and you can decide

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/uicases/startup/CreateProfileScreen.kt
> +    val presenter: CreateProfilePresenter = koinInject { parametersOf(navController) }
this effort would have been avoided if I could have finished the lifecycle binding before. It's ok, for this particular case its no big deal at least for now.

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/presentation/src/iosMain/kotlin/network/bisq/mobile/presentation/di/IosClientModule.kt
> +val iosClientModule = module {
same comments apply here as for androidClientModule

2024-11-19 00:05 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/ClientUserProfileServiceFacade.kt
> +    private val log = Logger.withTag("IosClientUserProfileController")
please use kotlin class dynamic naming for the tag (so the android client gets the right name)

2024-11-19 01:28 UTC, rodvar commented
@HenrikJannsen done this for you

 - https://github.com/bisq-network/bisq-mobile/pull/64
 
 you'll probably get conflicts with the CreateProfile screen related code on rebase. I humbly suggest that we keep the presenter view defined interface (you'll see why in the code) but it's up to you for this particular case. cheers!

2024-11-19 03:16 UTC, HenrikJannsen commented
> * I can't go past the screen when clicking next nothing happens and no error is logged

I commented out the code to go to next screen in the presenter for dev testing. see comments there. i wanted to test several use cases and as the UI is not yet prepared for that i did it with changing the presenter. I will add a commit to undo that. But would be good as next step to make the UI behaving to the intended use case.

1. After loading screen -> check if there is an existing user profile. 
1a. If there is an existing user profile, do not show create user profile screen, but show user profile is some not yet defined way (right top corner in Desktop shows user profile).
1b. If there is no existing user profile, show create profile screen.

Additionally: Show busy animation when generating keypair and when creating the profile. The domain model contains 2 boolean `inProgress` properties for that.

2024-11-19 03:22 UTC, HenrikJannsen commented
> Regarding the Ktor addition. I was working on this as well but in a separate new `networking` module in an effort to avoid making the androidModule grasp those dependencies when its not gonna be used.

Ah that is good. But maybe we call it 'client' instead of networking, as networking happens also in the node when all is delegated to the libraries.
Is it basically the code from shared.domain.client.
We should also move the Bisq2 replicated models (annotated with @Serializable) which are only used for client over there. 

Btw. I did not clean up the gradle dependencies, there might be too many and they should be moved to toml file.... also there are those issues with the exclusion of the logging lib... But I guess you have better ideas when it comes to gradle stuff..

2024-11-19 03:33 UTC, HenrikJannsen commented on bisqapps/androidClient/src/androidMain/kotlin/network/bisq/mobile/client/di/AndroidClientModule.kt
> +    single { ApiRequestService("10.0.2.2") }
I assume that is not in place yet, right? It also need to be customized when running on a device compared to simulator.

2024-11-19 04:00 UTC, rodvar commented on bisqapps/androidClient/src/androidMain/kotlin/network/bisq/mobile/client/di/AndroidClientModule.kt
> +    single { ApiRequestService("10.0.2.2") }
not in place yet - we can do it in the context of this PR if you like or on the next one (with the module refactor I was talking above)

2024-11-19 04:13 UTC, HenrikJannsen commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/di/AndroidNodeModule.kt
> +    single { AndroidApplicationService.Supplier() }
> Shouldn't then the AndroidApplicationService instance be configured here

If we manage to get the constructor arguments `context: Context, userDataDir: Path?` available in KOIN module, we can do that. But those data are only available when MainActivity is ready and we create KOIN earlier. But if you have any idea, feel free to change.

> the supplier injected into that service to provide for all the rest of the instances
If you mean how I interpret it, that's the case.
```
single<UserProfileServiceFacade> { NodeUserProfileServiceFacade(get(), get()) }
 
class NodeUserProfileServiceFacade(
    override val model: UserProfileModel,
    private val applicationServiceSupplier: AndroidApplicationService.Supplier
)
```

2024-11-19 04:41 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/di/AndroidNodeModule.kt
> +    single { AndroidApplicationService.Supplier() }
yep that's completely possible. Sure I can jump in after you are ready for the next review pass

2024-11-19 05:24 UTC, HenrikJannsen commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/ClientUserProfileServiceFacade.kt
> +    // TODO Dispatchers.IO is not supported on iOS. Either customize or find whats on iOS appropriate.
I saw you did it already. ;-)

2024-11-20 21:48 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/AndroidApplicationService.kt
> +    init {
I'll contribute with a commit for this

2024-11-20 21:53 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/presentation/NodeMainPresenter.kt
> +    // FIXME onViewAttached is called twice
I'll fix it in my contribution commit

2024-11-20 21:54 UTC, rodvar commented on bisqapps/androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/AndroidApplicationService.kt
> +class AndroidApplicationService(context: Context, userDataDir: Path?) :
I'll fix injection in my contribution commit

2024-11-20 22:16 UTC, rodvar commented on bisqapps/androidClient/src/androidMain/kotlin/network/bisq/mobile/client/di/AndroidClientModule.kt
> +    single { ApiRequestService(get(), "10.0.2.2") }
this hardcoded emulator ip will eventually be replaced by the "EnvironmentService" that will detect if its an emulator or not and return that ip or the actualy trusted node repository data - nothing that we need to do in this PR just leaving the comment

2024-11-20 22:23 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/service/ApiRequestService.kt
> +class ApiRequestService(private val httpClient: HttpClient, host: String) {
we don't want the networking client dependency in domain module because that's gonna go in the 3 apps and androidNode has its own networking already.

There will be a subsequent improvement PR to refactor this but good for now.

2024-11-20 22:28 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/UserProfileApiGateway.kt
> +            contextual(ByteArrayAsBase64Serializer)
shouldn't this be in the DI HttpClient provider?

2024-11-20 22:32 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/user_profile/UserProfileApiGateway.kt
> +        return json.decodeFromString(response)
This manual decoding that will be repeated all over can be avoided with the right setup of the HttpClient and changing the ApiRequestService to something like:

```
class ApiRequestService(private val httpClient: HttpClient) {

    suspend inline fun <reified T> post(endpoint: String, body: Any): T {
        return httpClient.post(endpoint) {
            setBody(body)
        }.body()
    }

    suspend inline fun <reified T> get(endpoint: String): T {
        return httpClient.get(endpoint).body()
    }
}
```

2024-11-20 22:33 UTC, rodvar commented on bisqapps/shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/uicases/startup/CreateProfilePresenter.kt
> +    private val _id = MutableStateFlow("")
cool :)

2024-11-21 22:15 UTC, rodvar commented on bisqapps/shared/domain/src/commonMain/kotlin/network/bisq/mobile/client/service/ApiRequestService.kt
> +class ApiRequestService(val httpClient: HttpClient, host: String) {
:heart:

2024-11-21 22:19 UTC, rodvar approved these changes
:tada:

2024-11-21 22:19 UTC, merged